### ISSUE TITLE
[improvement] edit foto biar tidak terkesan gepeng

### ISSUE THREAD

**Issue by achmadk** [razizs/exercise-1#2]
Halo @razizs , website-nya keren banget 👍 

Saya mau kasih saran buat bagusin tugas pertamanya @razizs . di kelas `main2`, edit css-nya menjadi

```css
.main2 {
  height: 100%;
  width: 100%;
  background-image: url(https://media.licdn.com/dms/image/C5603AQFFk9chNDCk1A/profile-displayphoto-shrink_200_200/0?e=1555545600&v=beta&t=c0ywII1_WjAvPA8Z_QU_8gbjmFqFj4IWeBMBE8ErLuo);
  background-size: 100%;
  background-position: center;
}
```
